### ISSUE TITLE
Is progressive enhancement for an optional minor feature eligible?

### ISSUE THREAD

**Issue by bkil** [macdonst/js-naked-day.org#10]
SecuChart is a CSS-only interactive comparison of messenger apps by features using generated combinatoric logic.

It provides for a rarely used expert function (`edit`) using JavaScript to generate a git diff itself. When JavaScript is disabled, this button is hidden but everything works all the same otherwise. Is it eligible or should we remove this button for everyone for the duration of the celebration?

https://bkil.gitlab.io/secuchart/

**Comment by macdonst** [comment]
@bkil the spirit of the day is to remove all scripts from your website to show folks it still works. I really like what you've done with secuchart.

**Comment by bkil** [comment]
Thank you for the quick answer. I've now removed all scripts.
