### ISSUE TITLE
Spurs break underlines

### ISSUE THREAD

**Issue by myfonj** [macdonst/js-naked-day.org#12]
<small>Super-niche and nitpicky bug report, maybe just a heads up:</small>

Newsreader's font capital letters spurs on bottom horizontal legs terminals descend below baseline, what in combination with `text-underline-offset` computed at around `1.2px` slightly unexpectedly interrupts link underlines under letters "L", "Z" and "E" in Firefox on Windows:

![Words "Chrome, Edge and Safari" in nice serif font and thick tight underline that does not go below descender of the letter "g". The underline is interrupted under the right side of the letter "E" in "Edge".](https://github.com/macdonst/js-naked-day.org/assets/1761395/fbf788fe-13ee-41e1-971a-33934fa7ba69)
![Capital Es in "Experience" and "Eden" interrupting an underline.](https://github.com/macdonst/js-naked-day.org/assets/1761395/2ccca512-82cf-48f2-8474-19be8e83b533)
![Capital Z in "Zach Leatherman" also interrupting an undeline.](https://github.com/macdonst/js-naked-day.org/assets/1761395/c1fc13be-352a-4bd9-a169-99966549f336)

Interestingly, in Chrome the `text-underline-offset` must be even tighter to produce similar result.

**Comment by macdonst** [comment]
Thanks for the issue @myfonj, I will let @colepeters know about it.

**Comment by colepeters** [comment]
Thanks for flagging this, @myfonj! I’ve fixed this in f4d714bae78ef1f8d9f377e1fd19e5a70f45746e
