### ISSUE TITLE
Quinck Portfolio

### ISSUE THREAD

**Issue by samuelemedici** [macdonst/js-naked-day.org#24]
Quinck is an italian startup I want to partecipate to this with our Portfolio made with Astro ([https://portfolio.quinck.io/]https://portfolio.quinck.io/)

I don't know if using Astro is considered cheating, but it's just a simple technical business card.

**Comment by macdonst** [comment]
@samuelemedici no, that's not considered cheating. Can you send a PR to add your page?

**Comment by samuelemedici** [comment]
> @samuelemedici no, that's not considered cheating. Can you send a PR to add your page?

Done!
